name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps (minimal for dry-run)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest
      - name: Run dry-run tests
        run: |
          python -m pytest -q tests/test_entsoe_dry_run.py
